export type ForgeSettingType =
  | 'boolean'
  | 'select'
  | 'text'
  | 'secret'
  | 'number'
  | 'list'
  | 'providerToggle'

export type ForgeSettingSensitivity = 'safe' | 'caution' | 'secret' | 'advanced'

export interface ForgeSettingOption {
  label: string
  value: string
}

export interface ForgeSetting {
  id: string
  label: string
  description?: string
  category: string
  type: ForgeSettingType
  value: unknown
  defaultValue: unknown
  options?: ForgeSettingOption[]
  provider?: string
  source?: string
  sensitivity: ForgeSettingSensitivity
  restartOrRescanRecommended?: boolean
  dryRunRequired?: boolean
  notes?: string
  coreMapping?: { section: string; key: string }
  appLabel: string
}

export interface ForgeProviderConfig {
  id: string
  name: string
  role: string
  enabled: boolean
  description: string
  fields: string[]
  hasCredential: boolean
  credentialLabel?: string
  credentialEnv?: string
  credentialKey?: string
  actions: string[]
}

export interface ForgeRewriteRule {
  id: string
  field: 'genre' | 'style' | 'label' | 'artist' | 'albumartist'
  from: string
  to: string
}

export interface ForgeSettingsState {
  providers: ForgeProviderConfig[]
  settings: Record<string, unknown>
  credentials: Record<string, string>
  rewriteRules: ForgeRewriteRule[]
  updateChannel: 'stable' | 'beta' | 'nightly'
  lastCheckedUpdate: string | null
  updateStatus: 'idle' | 'checking' | 'up_to_date' | 'available' | 'failed' | 'downloading' | 'ready'
  availableVersion: string | null
  updateReleaseNotes: string[]
}

export const defaultForgeSettingsState: ForgeSettingsState = {
  providers: [
    {
      id: 'musicbrainz',
      name: 'MusicBrainz',
      role: 'Identity authority',
      enabled: true,
      description: 'MBIDs, artist/album/track identity, release identity',
      fields: ['MBIDs', 'Artist identity', 'Album identity', 'Track identity', 'Release identity'],
      hasCredential: false,
      actions: ['Configure identity behavior', 'Test lookup'],
    },
    {
      id: 'discogs',
      name: 'Discogs',
      role: 'Catalog enrichment',
      enabled: true,
      description: 'Label, catalog number, barcode, country, format, release type, genre/style',
      fields: ['Label', 'Catalog number', 'Barcode', 'Country', 'Format', 'Release type', 'Genre', 'Style'],
      hasCredential: true,
      credentialLabel: 'Discogs token',
      credentialEnv: 'DISCOGS_TOKEN',
      credentialKey: 'discogs_token',
      actions: ['Configure catalog fields', 'Test lookup'],
    },
    {
      id: 'acoustid',
      name: 'AcoustID',
      role: 'Identifier',
      enabled: true,
      description: 'Fingerprint, AcoustID, identity matching',
      fields: ['Fingerprint', 'AcoustID', 'Identity matching'],
      hasCredential: true,
      credentialLabel: 'AcoustID API key',
      credentialEnv: 'ACOUSTID_API_KEY',
      credentialKey: 'acoustid_api_key',
      actions: ['Configure matching', 'Test fingerprint'],
    },
    {
      id: 'deezer',
      name: 'Deezer',
      role: 'Fallback provider',
      enabled: false,
      description: 'Genre, date, tracklist, duration, cover',
      fields: ['Genre', 'Date', 'Tracklist', 'Duration', 'Cover'],
      hasCredential: true,
      credentialLabel: 'Deezer API key',
      credentialEnv: 'DEEZER_API_KEY',
      credentialKey: 'deezer_api_key',
      actions: ['Enable fallback'],
    },
    {
      id: 'itunes',
      name: 'iTunes',
      role: 'Fallback provider',
      enabled: false,
      description: 'Genre, date, tracklist, duration, cover, explicit flag',
      fields: ['Genre', 'Date', 'Tracklist', 'Duration', 'Cover', 'Explicit'],
      hasCredential: false,
      actions: ['Configure storefront'],
    },
    {
      id: 'lastfm',
      name: 'Last.fm',
      role: 'Community enrichment',
      enabled: true,
      description: 'Tags, mood, style enrichment',
      fields: ['Tags', 'Mood', 'Style'],
      hasCredential: true,
      credentialLabel: 'Last.fm API key',
      credentialEnv: 'LASTFM_API_KEY',
      credentialKey: 'lastfm_api_key',
      actions: ['Configure enrichment'],
    },
    {
      id: 'lrclib',
      name: 'LRCLIB',
      role: 'Lyrics provider',
      enabled: true,
      description: 'Lyrics, synced lyrics',
      fields: ['Plain lyrics', 'Synced lyrics'],
      hasCredential: false,
      actions: ['Configure lyrics lookup'],
    },
    {
      id: 'genius',
      name: 'Genius',
      role: 'Advanced lyrics',
      enabled: false,
      description: 'Lyrics, annotations',
      fields: ['Lyrics', 'Annotations'],
      hasCredential: true,
      credentialLabel: 'Genius access token',
      credentialEnv: 'GENIUS_ACCESS_TOKEN',
      credentialKey: 'genius_access_token',
      actions: ['Configure (advanced)'],
    },
    {
      id: 'musixmatch',
      name: 'Musixmatch',
      role: 'Advanced lyrics',
      enabled: false,
      description: 'Lyrics, translations',
      fields: ['Lyrics', 'Translations'],
      hasCredential: true,
      credentialLabel: 'Musixmatch API key',
      credentialEnv: 'MUSIXMATCH_API_KEY',
      credentialKey: 'musixmatch_api_key',
      actions: ['Configure (advanced)'],
    },
    {
      id: 'audd',
      name: 'AudD',
      role: 'Audio recognition',
      enabled: false,
      description: 'Audio recognition, metadata lookup',
      fields: ['Audio recognition', 'Metadata lookup'],
      hasCredential: true,
      credentialLabel: 'AudD API key',
      credentialEnv: 'AUDD_API_KEY',
      credentialKey: 'audd_api_key',
      actions: ['Configure (advanced)'],
    },
  ],
  settings: {
    'metadata.prefer_original_date': true,
    'metadata.clean_bad_fields': true,
    'metadata.write_mbids': true,
    'metadata.protect_identity_fields': true,
    'metadata.conflict_policy': 'review',
    'metadata.min_confidence': 'medium',
    'metadata.multi_value_separator': '; ',
    'metadata.trim_values': true,
    'metadata.dedupe_values': true,
    'metadata.case_normalization': true,
    'metadata.review_low_confidence': true,
    'metadata.review_existing_mismatch': true,
    'cover.enabled': true,
    'cover.embed': true,
    'cover.save_folder_cover': false,
    'cover.filename': 'cover',
    'cover.min_confidence': 'medium',
    'cover.prefer_front': true,
    'cover.max_size_mb': 10,
    'lyrics.enabled': true,
    'lyrics.prefer_synced': true,
    'lyrics.allow_unsynced': true,
    'lyrics.prefer_local': true,
    'lyrics.prefer_existing': true,
    'lyrics.embed_lyrics': true,
    'lyrics.save_lrc': true,
    'lyrics.save_txt': false,
    'lyrics.cache_enabled': true,
    'lyrics.review_on_conflict': true,
    'lyrics.review_on_existing_mismatch': true,
    'lyrics.allow_instrumental': false,
    'lyrics.custom_http_enabled': false,
    'lyrics.custom_http_url': '',
    'audio.replaygain_enabled': true,
    'audio.replaygain_backend': 'ffmpeg',
    'audio.target_lufs': -18,
    'audio.write_track_gain': true,
    'audio.write_track_peak': true,
    'audio.write_album_gain': true,
    'audio.write_album_peak': true,
    'audio.write_loudness': true,
    'audio.skip_existing': true,
    'audio.key_detection_mode': 'disabled',
    'audio.key_min_confidence': 'medium',
    'audio.key_write_low_confidence': false,
    'audio.key_max_seconds': 90,
    'audio.key_segments': 6,
    'audio.key_timeout_seconds': 30,
    'safety.dry_run_first': true,
    'safety.require_confirmation': true,
    'safety.send_conflicts_to_review': true,
    'safety.never_overwrite_lyrics': true,
    'safety.never_replace_artwork': true,
    'safety.hide_advanced_metadata': true,
    'safety.show_catalog_fields': false,
    'safety.show_advanced_fields': false,
    'safety.track_provider_history': true,
    'safety.track_tag_sync': true,
    'safety.job_history_days': 30,
    'safety.prune_completed_jobs': true,
    'safety.auto_apply_safe': 'off',
    'safety.conflict_behavior': 'review',
    'advanced.database_auto_scan': false,
    'advanced.enrich_cover': false,
    'advanced.enrich_lyrics': false,
    'advanced.enrich_lastfm': true,
    'advanced.enrich_mood': true,
    'advanced.enrich_bpm': true,
    'advanced.enrich_features': true,
    'advanced.enrich_acoustid': true,
    'advanced.enrich_replaygain': false,
    'advanced.output_verbose': false,
    'advanced.output_debug': false,
  },
  credentials: {
    lastfm_api_key: '',
    discogs_token: '',
    acoustid_api_key: '',
    deezer_api_key: '',
    spotify_client_id: '',
    spotify_client_secret: '',
    genius_access_token: '',
    musixmatch_api_key: '',
    audd_api_key: '',
  },
  rewriteRules: [
    { id: 'rr-1', field: 'genre', from: 'kpop', to: 'K-pop' },
    { id: 'rr-2', field: 'style', from: 'Prog Metal', to: 'Progressive Metal' },
    { id: 'rr-3', field: 'style', from: 'technical death', to: 'Technical Death Metal' },
  ],
  updateChannel: 'stable',
  lastCheckedUpdate: null,
  updateStatus: 'idle',
  availableVersion: null,
  updateReleaseNotes: [],
}

export const forgeSettingsCatalog: ForgeSetting[] = [
  // Metadata Providers
  {
    id: 'metadata_providers.enabled',
    label: 'Enable metadata providers',
    category: 'Metadata Providers',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'metadata_providers', key: 'enabled' },
    appLabel: 'Enable metadata providers',
  },
  {
    id: 'metadata_providers.max_active',
    label: 'Max active providers',
    category: 'Metadata Providers',
    type: 'number',
    value: 2,
    defaultValue: 2,
    sensitivity: 'advanced',
    notes: 'Does not count identifier providers',
    coreMapping: { section: 'metadata_providers', key: 'max_active' },
    appLabel: 'Max active providers',
  },
  {
    id: 'metadata_providers.allow_more_providers',
    label: 'Allow more providers',
    category: 'Metadata Providers',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'metadata_providers', key: 'allow_more_providers' },
    appLabel: 'Allow more providers',
  },
  // Tags & Metadata
  {
    id: 'metadata.prefer_original_date',
    label: 'Prefer original date',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'metadata', key: 'prefer_original_date' },
    appLabel: 'Prefer original release date',
  },
  {
    id: 'metadata.clean_bad_fields',
    label: 'Clean bad fields',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'metadata', key: 'clean_bad_fields' },
    appLabel: 'Clean invalid fields',
  },
  {
    id: 'metadata.write_mbids',
    label: 'Write MBIDs',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'metadata', key: 'write_mbids' },
    appLabel: 'Write MusicBrainz IDs',
  },
  {
    id: 'metadata.protect_identity_fields',
    label: 'Protect identity fields',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    notes: 'Identity fields require explicit confirmation before overwrite',
    coreMapping: { section: 'sync', key: 'protect_identity_fields' },
    appLabel: 'Protect identity fields',
  },
  {
    id: 'metadata.conflict_policy',
    label: 'Conflict policy',
    category: 'Tags & Metadata',
    type: 'select',
    value: 'review',
    defaultValue: 'review',
    options: [
      { label: 'Send to Review', value: 'review' },
      { label: 'Skip', value: 'skip' },
      { label: 'Prefer current', value: 'prefer_current' },
      { label: 'Prefer provider', value: 'prefer_provider' },
    ],
    sensitivity: 'caution',
    coreMapping: { section: 'sync', key: 'conflict_policy' },
    appLabel: 'Conflict policy',
  },
  {
    id: 'metadata.min_confidence',
    label: 'Minimum confidence',
    category: 'Tags & Metadata',
    type: 'select',
    value: 'medium',
    defaultValue: 'medium',
    options: [
      { label: 'Low', value: 'low' },
      { label: 'Medium', value: 'medium' },
      { label: 'High', value: 'high' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'metadata_providers', key: 'min_confidence' },
    appLabel: 'Minimum provider confidence',
  },
  {
    id: 'metadata.multi_value_separator',
    label: 'Multi-value separator',
    category: 'Tags & Metadata',
    type: 'select',
    value: '; ',
    defaultValue: '; ',
    options: [
      { label: 'Semicolon', value: '; ' },
      { label: 'Slash', value: ' / ' },
      { label: 'Comma', value: ', ' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'rewrite.multi_value', key: 'separator' },
    appLabel: 'Multi-value tag separator',
  },
  {
    id: 'metadata.trim_values',
    label: 'Trim values',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'rewrite.multi_value', key: 'trim_values' },
    appLabel: 'Trim tag values',
  },
  {
    id: 'metadata.dedupe_values',
    label: 'Deduplicate values',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'rewrite.multi_value', key: 'dedupe_values' },
    appLabel: 'Deduplicate multi-value tags',
  },
  {
    id: 'metadata.case_normalization',
    label: 'Normalize case',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'rewrite', key: 'case_sensitive' },
    appLabel: 'Normalize genre/style case',
    notes: 'Inverted from case_sensitive config',
  },
  {
    id: 'metadata.review_low_confidence',
    label: 'Review low-confidence matches',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Review low-confidence matches',
  },
  {
    id: 'metadata.review_existing_mismatch',
    label: 'Review existing mismatch',
    category: 'Tags & Metadata',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Review when existing values differ',
  },
  // Artwork
  {
    id: 'cover.enabled',
    label: 'Enable artwork fixes',
    category: 'Artwork',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'enabled' },
    appLabel: 'Enable artwork fixes',
  },
  {
    id: 'cover.embed',
    label: 'Embed artwork into tags',
    category: 'Artwork',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'embed' },
    appLabel: 'Embed artwork into tags',
  },
  {
    id: 'cover.save_folder_cover',
    label: 'Save folder cover file',
    category: 'Artwork',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'save_folder_cover' },
    appLabel: 'Save folder cover file',
  },
  {
    id: 'cover.filename',
    label: 'Folder cover filename',
    category: 'Artwork',
    type: 'text',
    value: 'cover',
    defaultValue: 'cover',
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'filename' },
    appLabel: 'Folder cover filename',
  },
  {
    id: 'cover.min_confidence',
    label: 'Minimum confidence',
    category: 'Artwork',
    type: 'select',
    value: 'medium',
    defaultValue: 'medium',
    options: [
      { label: 'Low', value: 'low' },
      { label: 'Medium', value: 'medium' },
      { label: 'High', value: 'high' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'min_confidence' },
    appLabel: 'Minimum artwork confidence',
  },
  {
    id: 'cover.prefer_front',
    label: 'Prefer front cover',
    category: 'Artwork',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'prefer_front' },
    appLabel: 'Prefer front cover',
  },
  {
    id: 'cover.max_size_mb',
    label: 'Max image size',
    category: 'Artwork',
    type: 'number',
    value: 10,
    defaultValue: 10,
    sensitivity: 'safe',
    coreMapping: { section: 'cover', key: 'max_size_mb' },
    appLabel: 'Max image size (MB)',
  },
  // Lyrics
  {
    id: 'lyrics.enabled',
    label: 'Enable lyrics fixes',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'enabled' },
    appLabel: 'Enable lyrics fixes',
  },
  {
    id: 'lyrics.prefer_synced',
    label: 'Prefer synced lyrics',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'prefer_synced' },
    appLabel: 'Prefer synced lyrics',
  },
  {
    id: 'lyrics.allow_unsynced',
    label: 'Allow unsynced fallback',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'allow_unsynced' },
    appLabel: 'Allow unsynced fallback',
  },
  {
    id: 'lyrics.prefer_local',
    label: 'Prefer local lyrics',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'prefer_local' },
    appLabel: 'Prefer local lyrics',
  },
  {
    id: 'lyrics.prefer_existing',
    label: 'Preserve existing lyrics',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'prefer_existing' },
    appLabel: 'Preserve existing lyrics',
  },
  {
    id: 'lyrics.embed_lyrics',
    label: 'Embed lyrics',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'embed_lyrics' },
    appLabel: 'Embed lyrics into tags',
  },
  {
    id: 'lyrics.save_lrc',
    label: 'Save sidecar .lrc',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'save_lrc' },
    appLabel: 'Save sidecar .lrc',
  },
  {
    id: 'lyrics.save_txt',
    label: 'Save .txt',
    category: 'Lyrics',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'save_txt' },
    appLabel: 'Save .txt',
  },
  {
    id: 'lyrics.cache_enabled',
    label: 'Cache lyrics lookups',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'cache_enabled' },
    appLabel: 'Cache lyrics lookups',
  },
  {
    id: 'lyrics.review_on_conflict',
    label: 'Review conflicts',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'review_on_conflict' },
    appLabel: 'Review conflicting lyrics',
  },
  {
    id: 'lyrics.review_on_existing_mismatch',
    label: 'Review existing mismatches',
    category: 'Lyrics',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'review_on_existing_mismatch' },
    appLabel: 'Review when existing lyrics differ',
  },
  {
    id: 'lyrics.allow_instrumental',
    label: 'Allow instrumental results',
    category: 'Lyrics',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'safe',
    coreMapping: { section: 'lyrics', key: 'allow_instrumental' },
    appLabel: 'Allow instrumental results',
  },
  {
    id: 'lyrics.custom_http_enabled',
    label: 'Custom lyrics endpoint',
    category: 'Lyrics',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'lyrics.provider_settings.custom_http', key: 'enabled' },
    appLabel: 'Enable custom lyrics endpoint',
  },
  {
    id: 'lyrics.custom_http_url',
    label: 'Custom endpoint URL',
    category: 'Lyrics',
    type: 'text',
    value: '',
    defaultValue: '',
    sensitivity: 'advanced',
    coreMapping: { section: 'lyrics.provider_settings.custom_http', key: 'base_url' },
    appLabel: 'Custom endpoint URL',
  },
  // Audio
  {
    id: 'audio.replaygain_enabled',
    label: 'Enable ReplayGain',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'replaygain_enabled' },
    appLabel: 'Enable ReplayGain',
  },
  {
    id: 'audio.replaygain_backend',
    label: 'ReplayGain backend',
    category: 'Audio',
    type: 'select',
    value: 'ffmpeg',
    defaultValue: 'ffmpeg',
    options: [
      { label: 'ffmpeg', value: 'ffmpeg' },
      { label: 'Mock / Portable', value: 'portable' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'replaygain_backend' },
    appLabel: 'ReplayGain backend',
  },
  {
    id: 'audio.target_lufs',
    label: 'Target LUFS',
    category: 'Audio',
    type: 'number',
    value: -18,
    defaultValue: -18,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'target_lufs' },
    appLabel: 'Target LUFS',
  },
  {
    id: 'audio.write_track_gain',
    label: 'Write track gain',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'write_track_gain' },
    appLabel: 'Write track gain',
  },
  {
    id: 'audio.write_track_peak',
    label: 'Write track peak',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'write_track_peak' },
    appLabel: 'Write track peak',
  },
  {
    id: 'audio.write_album_gain',
    label: 'Write album gain',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'write_album_gain' },
    appLabel: 'Write album gain',
  },
  {
    id: 'audio.write_album_peak',
    label: 'Write album peak',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'write_album_peak' },
    appLabel: 'Write album peak',
  },
  {
    id: 'audio.write_loudness',
    label: 'Write loudness',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'write_loudness' },
    appLabel: 'Write loudness',
  },
  {
    id: 'audio.skip_existing',
    label: 'Skip existing values',
    category: 'Audio',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'audio', key: 'skip_existing' },
    appLabel: 'Skip existing audio values',
  },
  {
    id: 'audio.key_detection_mode',
    label: 'Key detection mode',
    category: 'Audio',
    type: 'select',
    value: 'disabled',
    defaultValue: 'disabled',
    options: [
      { label: 'Disabled', value: 'disabled' },
      { label: 'Auto', value: 'auto' },
      { label: 'Portable basic', value: 'portable_basic' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'audio.key_detection', key: 'backend' },
    appLabel: 'Key detection mode',
    notes: 'Maps to backend config value',
  },
  {
    id: 'audio.key_min_confidence',
    label: 'Minimum key confidence',
    category: 'Audio',
    type: 'select',
    value: 'medium',
    defaultValue: 'medium',
    options: [
      { label: 'Low', value: 'low' },
      { label: 'Medium', value: 'medium' },
      { label: 'High', value: 'high' },
    ],
    sensitivity: 'safe',
    coreMapping: { section: 'audio.key_detection', key: 'min_confidence' },
    appLabel: 'Minimum key confidence',
  },
  {
    id: 'audio.key_write_low_confidence',
    label: 'Write low-confidence key',
    category: 'Audio',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'caution',
    coreMapping: { section: 'audio.key_detection', key: 'write_low_confidence' },
    appLabel: 'Write low-confidence key estimates',
  },
  {
    id: 'audio.key_max_seconds',
    label: 'Max analysis seconds',
    category: 'Audio',
    type: 'number',
    value: 90,
    defaultValue: 90,
    sensitivity: 'advanced',
    coreMapping: { section: 'audio.key_detection.portable_basic', key: 'max_seconds' },
    appLabel: 'Max analysis seconds',
  },
  {
    id: 'audio.key_segments',
    label: 'Analysis segments',
    category: 'Audio',
    type: 'number',
    value: 6,
    defaultValue: 6,
    sensitivity: 'advanced',
    coreMapping: { section: 'audio.key_detection.portable_basic', key: 'segments' },
    appLabel: 'Analysis segments',
  },
  {
    id: 'audio.key_timeout_seconds',
    label: 'Analysis timeout',
    category: 'Audio',
    type: 'number',
    value: 30,
    defaultValue: 30,
    sensitivity: 'advanced',
    coreMapping: { section: 'audio.key_detection.portable_basic', key: 'timeout_seconds' },
    appLabel: 'Analysis timeout (seconds)',
  },
  // Safety & Review
  {
    id: 'safety.dry_run_first',
    label: 'Dry-run first mode',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    notes: 'All write-capable workflows default to dry-run',
    appLabel: 'Dry-run first mode',
  },
  {
    id: 'safety.require_confirmation',
    label: 'Require confirmation',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Require confirmation before applying',
  },
  {
    id: 'safety.send_conflicts_to_review',
    label: 'Send conflicts to review',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Send conflicts to review queue',
  },
  {
    id: 'safety.never_overwrite_lyrics',
    label: 'Never overwrite lyrics without review',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Never overwrite lyrics without review',
  },
  {
    id: 'safety.never_replace_artwork',
    label: 'Never replace valid artwork',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Never replace valid artwork without comparison',
  },
  {
    id: 'safety.hide_advanced_metadata',
    label: 'Hide advanced metadata by default',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    appLabel: 'Hide advanced metadata by default',
  },
  {
    id: 'safety.show_catalog_fields',
    label: 'Show catalog fields',
    category: 'Safety & Review',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'safe',
    coreMapping: { section: 'audit', key: 'show_catalog_fields' },
    appLabel: 'Show catalog fields in audit',
  },
  {
    id: 'safety.show_advanced_fields',
    label: 'Show advanced fields',
    category: 'Safety & Review',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'safe',
    coreMapping: { section: 'audit', key: 'show_advanced_fields' },
    appLabel: 'Show advanced fields in audit',
  },
  {
    id: 'safety.track_provider_history',
    label: 'Track provider history',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'database', key: 'track_provider_history' },
    appLabel: 'Track provider history',
  },
  {
    id: 'safety.track_tag_sync',
    label: 'Track tag sync',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    coreMapping: { section: 'database', key: 'track_tag_sync' },
    appLabel: 'Track tag sync',
  },
  {
    id: 'safety.job_history_days',
    label: 'Job history days',
    category: 'Safety & Review',
    type: 'number',
    value: 30,
    defaultValue: 30,
    sensitivity: 'safe',
    coreMapping: { section: 'jobs', key: 'history_days' },
    appLabel: 'Job history retention (days)',
  },
  {
    id: 'safety.prune_completed_jobs',
    label: 'Prune completed jobs',
    category: 'Safety & Review',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'safe',
    notes: 'Mock-only in this preview',
    coreMapping: { section: 'jobs', key: 'prune_completed' },
    appLabel: 'Prune completed jobs',
  },
  {
    id: 'safety.auto_apply_safe',
    label: 'Auto-apply safe fixes',
    category: 'Safety & Review',
    type: 'select',
    value: 'off',
    defaultValue: 'off',
    options: [
      { label: 'Off', value: 'off' },
      { label: 'Ask every time', value: 'ask' },
      { label: 'Apply only empty fields', value: 'empty_only' },
    ],
    sensitivity: 'caution',
    appLabel: 'Auto-apply safe fixes',
  },
  {
    id: 'safety.conflict_behavior',
    label: 'Conflict behavior',
    category: 'Safety & Review',
    type: 'select',
    value: 'review',
    defaultValue: 'review',
    options: [
      { label: 'Always review', value: 'review' },
      { label: 'Prefer current', value: 'prefer_current' },
      { label: 'Prefer provider', value: 'prefer_provider' },
      { label: 'Skip', value: 'skip' },
    ],
    sensitivity: 'caution',
    appLabel: 'Conflict behavior',
  },
  // Advanced
  {
    id: 'advanced.database_auto_scan',
    label: 'Auto-scan database',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'database', key: 'auto_scan' },
    appLabel: 'Auto-scan database',
  },
  {
    id: 'advanced.enrich_cover',
    label: 'Include cover in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_cover' },
    appLabel: 'Include cover in full enrich',
  },
  {
    id: 'advanced.enrich_lyrics',
    label: 'Include lyrics in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_lyrics' },
    appLabel: 'Include lyrics in full enrich',
  },
  {
    id: 'advanced.enrich_lastfm',
    label: 'Include Last.fm in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_lastfm' },
    appLabel: 'Include Last.fm in full enrich',
  },
  {
    id: 'advanced.enrich_mood',
    label: 'Include mood in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_mood' },
    appLabel: 'Include mood in full enrich',
  },
  {
    id: 'advanced.enrich_bpm',
    label: 'Include BPM in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_bpm' },
    appLabel: 'Include BPM in full enrich',
  },
  {
    id: 'advanced.enrich_features',
    label: 'Include features in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_features' },
    appLabel: 'Include features in full enrich',
  },
  {
    id: 'advanced.enrich_acoustid',
    label: 'Include AcoustID in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: true,
    defaultValue: true,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_acoustid' },
    appLabel: 'Include AcoustID in full enrich',
  },
  {
    id: 'advanced.enrich_replaygain',
    label: 'Include ReplayGain in full enrich',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    coreMapping: { section: 'enrich', key: 'full_includes_replaygain' },
    appLabel: 'Include ReplayGain in full enrich',
  },
  {
    id: 'advanced.output_verbose',
    label: 'Verbose output',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    notes: 'Mock-only in this preview',
    coreMapping: { section: 'output', key: 'verbose' },
    appLabel: 'Verbose output',
  },
  {
    id: 'advanced.output_debug',
    label: 'Debug output',
    category: 'Advanced',
    type: 'boolean',
    value: false,
    defaultValue: false,
    sensitivity: 'advanced',
    notes: 'Mock-only in this preview',
    coreMapping: { section: 'output', key: 'debug' },
    appLabel: 'Debug output',
  },
]
