export type AnchorInteractionStatus =
  | 'not implemented'
  | 'partial'
  | 'implemented'
  | 'needs QA'

export type AnchorInteractionArea = 'home' | 'servers' | 'library' | 'activity'

export type AnchorInteraction = {
  id: string
  area: AnchorInteractionArea
  trigger: string
  surface: string
  mockState: string
  forbidden: string
  status: AnchorInteractionStatus
}

export const anchorInteractions: AnchorInteraction[] = [
  {
    id: 'home-settings',
    area: 'home',
    trigger: 'Settings icon',
    surface: 'Anchor settings sheet',
    mockState: 'Open settings overlay',
    forbidden: 'Read or write real settings',
    status: 'implemented',
  },
  {
    id: 'home-stop-server',
    area: 'home',
    trigger: 'Stop server button',
    surface: 'Confirmation dialog',
    mockState: 'Set mock server to stopped on confirm',
    forbidden: 'Stop real servers or processes',
    status: 'implemented',
  },
  {
    id: 'home-restart',
    area: 'home',
    trigger: 'Restart button',
    surface: 'Restart confirmation or progress state',
    mockState: 'Move through restarting back to active',
    forbidden: 'Call real server controls',
    status: 'implemented',
  },
  {
    id: 'home-library-card',
    area: 'home',
    trigger: 'Library card',
    surface: 'Library tab',
    mockState: 'Switch active Anchor tab to library',
    forbidden: 'Access a real library',
    status: 'implemented',
  },
  {
    id: 'home-copy-address',
    area: 'home',
    trigger: 'Copy address quick action',
    surface: 'Copied toast',
    mockState: 'Show mock toast',
    forbidden: 'Perform network action or expose non-mock addresses',
    status: 'implemented',
  },
  {
    id: 'home-show-qr-code',
    area: 'home',
    trigger: 'Show QR code quick action',
    surface: 'Mock QR code sheet',
    mockState: 'Open QR overlay',
    forbidden: 'Encode secrets or real connection details',
    status: 'implemented',
  },
  {
    id: 'home-refresh-library',
    area: 'home',
    trigger: 'Refresh library quick action',
    surface: 'Scan progress sheet',
    mockState: 'Move mock scan through idle, scanning, complete or failed',
    forbidden: 'Scan files or call a backend',
    status: 'implemented',
  },
  {
    id: 'servers-add-server',
    area: 'servers',
    trigger: 'Add server plus icon',
    surface: 'Add server sheet',
    mockState: 'Open add-server overlay and show toast-only add feedback',
    forbidden: 'Attempt discovery, connection or credential handling',
    status: 'implemented',
  },
  {
    id: 'servers-navidrome-details',
    area: 'servers',
    trigger: 'Navidrome card',
    surface: 'Server details sheet or expanded details',
    mockState: 'Select mock Navidrome server',
    forbidden: 'Query real server status',
    status: 'implemented',
  },
  {
    id: 'servers-menu',
    area: 'servers',
    trigger: 'Server menu icon',
    surface: 'Server menu sheet',
    mockState: 'Open menu, show toast feedback, disable locally or confirm removal',
    forbidden: 'Delete or edit real server config',
    status: 'implemented',
  },
  {
    id: 'servers-settings',
    area: 'servers',
    trigger: 'Settings button',
    surface: 'Navidrome Settings sheet',
    mockState: 'Open curated mock navidrome.toml settings center',
    forbidden: 'Read or write real server config',
    status: 'implemented',
  },
  {
    id: 'servers-navidrome-configure',
    area: 'servers',
    trigger: 'Configure Navidrome from details or server menu',
    surface: 'Navidrome Settings sheet',
    mockState: 'Open settings center with category navigation, local draft editing, previews, dry-run, apply and reset',
    forbidden: 'Call Anchor Core, Navidrome, filesystem, network, config files, ports or secrets',
    status: 'implemented',
  },
  {
    id: 'servers-navidrome-settings-categories',
    area: 'servers',
    trigger: 'Navidrome Settings category chips',
    surface: 'Category-specific settings rows',
    mockState: 'Switch visible category locally',
    forbidden: 'Load settings from real navidrome.toml',
    status: 'implemented',
  },
  {
    id: 'servers-navidrome-settings-preview',
    area: 'servers',
    trigger: 'Advanced TOML/env preview and Preview changes',
    surface: 'Display-only generated previews and dry-run sheet',
    mockState: 'Compute previews from local draft state',
    forbidden: 'Write files, read files, call APIs or expose secrets',
    status: 'implemented',
  },
  {
    id: 'servers-view-logs',
    area: 'servers',
    trigger: 'View logs button',
    surface: 'Mock log viewer',
    mockState: 'Open logs overlay',
    forbidden: 'Read real logs, files or process output',
    status: 'implemented',
  },
  {
    id: 'servers-jellyfin-coming-soon',
    area: 'servers',
    trigger: 'Jellyfin coming-soon card',
    surface: 'Coming-soon sheet or tooltip',
    mockState: 'Open coming-soon overlay',
    forbidden: 'Discover or connect to Jellyfin',
    status: 'implemented',
  },
  {
    id: 'servers-emby-coming-soon',
    area: 'servers',
    trigger: 'Emby coming-soon card',
    surface: 'Coming-soon sheet or tooltip',
    mockState: 'Open coming-soon overlay',
    forbidden: 'Discover or connect to Emby',
    status: 'implemented',
  },
  {
    id: 'library-change-folder',
    area: 'library',
    trigger: 'Change folder row',
    surface: 'Folder picker mock',
    mockState: 'Select fake display path only',
    forbidden: 'Open filesystem, file picker or FileReader',
    status: 'implemented',
  },
  {
    id: 'library-refresh',
    area: 'library',
    trigger: 'Refresh library row',
    surface: 'Scan progress sheet',
    mockState: 'Move through scanning, scanned or failed',
    forbidden: 'Scan media or read metadata',
    status: 'implemented',
  },
  {
    id: 'library-verify-access',
    area: 'library',
    trigger: 'Verify access row',
    surface: 'Access verification result sheet',
    mockState: 'Show accessible, warning or denied result',
    forbidden: 'Probe real permissions or paths',
    status: 'implemented',
  },
  {
    id: 'library-settings',
    area: 'library',
    trigger: 'Library settings row',
    surface: 'Library settings sheet',
    mockState: 'Open library settings overlay',
    forbidden: 'Persist real settings',
    status: 'implemented',
  },
  {
    id: 'library-stats-detail',
    area: 'library',
    trigger: 'Stats row',
    surface: 'Stats detail sheet',
    mockState: 'Open static stats detail',
    forbidden: 'Query a real library',
    status: 'implemented',
  },
  {
    id: 'library-scan-history',
    area: 'library',
    trigger: 'Last scan or Duration footer',
    surface: 'Scan history sheet',
    mockState: 'Open static scan history',
    forbidden: 'Read real scan logs',
    status: 'implemented',
  },
  {
    id: 'activity-filter',
    area: 'activity',
    trigger: 'Filter icon',
    surface: 'Activity filter sheet',
    mockState: 'Filter static mock activity',
    forbidden: 'Query or filter real logs',
    status: 'not implemented',
  },
  {
    id: 'activity-details',
    area: 'activity',
    trigger: 'Details buttons',
    surface: 'Activity detail sheet',
    mockState: 'Select static mock event',
    forbidden: 'Read real diagnostics',
    status: 'not implemented',
  },
  {
    id: 'activity-startup-failed',
    area: 'activity',
    trigger: 'Startup failed event',
    surface: 'Error detail sheet',
    mockState: 'Show port-in-use mock guidance',
    forbidden: 'Check real ports, processes or network state',
    status: 'not implemented',
  },
  {
    id: 'activity-item-tap',
    area: 'activity',
    trigger: 'Activity item tap',
    surface: 'Activity detail sheet',
    mockState: 'Select static mock event',
    forbidden: 'Read real logs or diagnostics',
    status: 'not implemented',
  },
]
